#!/usr/bin/env ruby
# ~/multi_scale_24f/w6_auto_git/auto_git_rev/s7_command_line
# auto_git~command_line

require 'command_line/global'
require 'colorize'

opts = {}
case ARGV[0]
when '-d'
  puts 'dryrun.'
  opts[:dryrun] = true
when '-m'
  opts[:message] = ARGV[1]
end

commit_command = opts[:message] ?
                   "git commit -m \'#{opts[:message]}\'" :
                   "git commit"

["git add -A",
commit_command, 
"git pull origin main",
"git push origin main"].each do |command|
  puts command.cyan
  puts ''
  next if opts[:dryrun]
  res = command_line command
  puts res.stderr.yellow
  puts res.stdout.green
end
