#!/usr/bin/env ruby

# boolean , true, false
# falsey , false, nil
# truthy , other
dryrun = true 

["git add -A",
"git commit",
#puts "git commit -m \'first commit\'"
"git pull origin main",
"git push origin main"].each do |comm|
  puts comm
end
