#!/usr/bin/bash

if [ $# -ne 1 ]; then
    explorer.exe .
else
    if [[ "$1" == *http* ]]; then
	explorer.exe "$1"
    elif [ -e "$1" ]; then
        powershell.exe /c start "$(wslpath -w "$1")" 2> /dev/null
    else
        echo "open: $1 : No such file or directory"
    fi
fi

