#!/usr/bin/env python3
import sys
import subprocess
import os

if len(sys.argv) != 2:
    subprocess.run(["explorer.exe", "."])
else:
    arg = sys.argv[1]
    if "http" in arg:
        subprocess.run(["explorer.exe", arg])
    elif os.path.exists(arg):
        try:
            wslpath_result = subprocess.run(["wslpath", "-w", arg],
                                            capture_output=True, text=True, check=True)
            windows_path = wslpath_result.stdout.strip()
            subprocess.run(["powershell.exe", "/c", "start",
                            windows_path], check=True)
        except subprocess.CalledProcessError:
            print(f"open: {arg} : Failed to open")
    else:
        print(f"open: {arg} : No such file or directory")
	
