#!/usr/bin/env python3
import glob
import os
import re
import sys

def tidy(recursive=False):
    """Removes junk files."""
    if recursive:
        dirs = ['./**/*', './**/.*']
    else:
        dirs = ['./*', './.*']

    count = 0
    for pattern in dirs:
        for file in glob.glob(pattern, recursive=True):
            regexp = re.compile(r"(.+~$)|(.+\#$)|(.+\.#.+)|(~\$.+)|(.+\.log$)|(.+\.aux$)|(.+\.bak$)|(.+\.dvi$)|(.+\.synctex.gz$)|(.+\.out$)|(.+-jvsc-.+.ipynb)")
            if regexp.search(file):
                try:
                    # print(f"rm {file}") # noop: true, verbose: true
                    os.remove(file)
                    count += 1
                    print(f"removed {file}")
                except OSError as e:
                    print(f"Error removing {file}: {e}")

    print(f"rm {count} junk files.")

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == '-r':
        tidy(recursive=True)
    else:
        tidy()
	