#!/usr/bin/env ruby

if ARGV[0] == '-d'
  puts 'dryrun.'
  dryrun = true
end

["git add -A",
"git commit",
#puts "git commit -m \'first commit\'"
"git pull origin main",
"git push origin main"].each do |comm|
  puts comm
  if dryrun
  else
    system comm
  end
end
