#!/usr/bin/env ruby

opts = {}
opts[:dryrun] = false
if ARGV[0] == '-d'
  puts 'dryrun.'
  opts[:dryrun] = true
end

["git add -A",
"git commit",
"git pull origin main",
"git push origin main"].each do |comm|
  puts comm
  next if opts[:dryrun]
  system comm 
end
