#!/usr/bin/env ruby
require 'colorize'

opts = {}
case ARGV[0]
when '-d'
  puts 'dryrun.'
  opts[:dryrun] = true
elsif ARGV[0] == '-m'
  opts[:message] = ARGV[1]
end

["git add -A",
"git commit",
"git pull origin main",
"git push origin main"].each do |comm|
  puts comm.green
  puts ''
  unless opts[:dryrun]
    system comm
  end
end
