#!/usr/bin/env ruby
# coding: utf-8
require 'colorize'

opts = {}
opts[:dryrun] = false
if ARGV[0] == '-d'
  puts 'dryrun.'
  opts[:dryrun] = true
elsif ARGV[0] == '-m'
  opts[:message] = ARGV[1]
end

message  = if opts[:message]
             "git commit -m \'#{opts[:message]}\'"
           else
             "git commit"
           end

["git add -A",
message,
"git pull origin main",
"git push origin main"].each do |comm|
  puts comm.green
  puts ''
  unless opts[:dryrun]
    system comm
  end
end

puts "git stash # 変更の取り消し"
puts "git log --graph --oneline # short log"
